---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ec2operator-cloud-infra-group-io-cloud-infra-group-io-v1alpha1-awsvpcendpointservice
  failurePolicy: Fail
  name: vawsvpcendpointservice-v1alpha1.kb.io
  rules:
  - apiGroups:
    - ec2operator.cloud-infra-group.io.cloud-infra-group.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsvpcendpointservices
  sideEffects: None
