# permissions for end users to view awsvpcendpointservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ec2-operator
    app.kubernetes.io/managed-by: kustomize
  name: awsvpcendpointservice-viewer-role
rules:
- apiGroups:
  - ec2operator.cloud-infra-group.io.cloud-infra-group.io
  resources:
  - awsvpcendpointservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ec2operator.cloud-infra-group.io.cloud-infra-group.io
  resources:
  - awsvpcendpointservices/status
  verbs:
  - get
