# permissions for end users to view instances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instance-viewer-role
rules:
- apiGroups:
  - ec2.cattle.io
  resources:
  - instances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ec2.cattle.io
  resources:
  - instances/status
  verbs:
  - get
