---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ec2operator.cloud-infra-group.io.cloud-infra-group.io
  resources:
  - awsvpcendpointserviceprincipals
  - awsvpcendpointservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ec2operator.cloud-infra-group.io.cloud-infra-group.io
  resources:
  - awsvpcendpointserviceprincipals/finalizers
  - awsvpcendpointservices/finalizers
  verbs:
  - update
- apiGroups:
  - ec2operator.cloud-infra-group.io.cloud-infra-group.io
  resources:
  - awsvpcendpointserviceprincipals/status
  - awsvpcendpointservices/status
  verbs:
  - get
  - patch
  - update
