apiVersion: ec2.cattle.io/v1alpha1
kind: ImportKeyPair
metadata:
  name: importkeypair-sample
spec:
  keyName: mycustom-import-keypair
  publicKey: base64encodedkey
  tagSpecification:
    - name: MyTag
      value: MyValue
  secret: k8s-secret-with-aws-keypair
  region: aws-region
